#!/bin/zsh

PKT_LIMIT=25

INTERVAL_LOWER_LIMIT=1000       # 1ms
INTERVAL_UPPER_LIMIT=100000     # 100ms

SLEEP_UPPER_LIMIT=5

LOOP_LOWER_LIMIT=50
LOOP_UPPER_LIMIT=100

INTERVAL_DIFF=$((INTERVAL_UPPER_LIMIT-INTERVAL_LOWER_LIMIT+1))
LOOP_DIFF=$((LOOP_UPPER_LIMIT-LOOP_LOWER_LIMIT+1))  
LOOP_COUNT=$(($(($RANDOM%$LOOP_DIFF))+LOOP_LOWER_LIMIT))

# Should be random as well.
for i in `seq 1 $LOOP_COUNT`
do
    INTERVAL=$(($(($RANDOM%$INTERVAL_DIFF))+INTERVAL_LOWER_LIMIT))
    hping3 -q -c $(($(($RANDOM%$PKT_LIMIT))+1)) -i u$((INTERVAL)) --keep 10.0.0.$(($(($(($RANDOM%3))+1))*2))
    sleep $(($((RANDOM/32768.0))*SLEEP_UPPER_LIMIT))
done
